build:
  version: 1.23.4

loans:
  message: "Welcome to my bank loans related QA APIs "
  contactDetails:
    name: "Schrader ASAC - QA Lead"
    email: "ASACS@bank.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467